### ISSUE TITLE
How to find your paper?

### ISSUE THREAD

**Issue by ghost** [ricardoCyy/Singapore_Bike_Visualization#1]
You've done a great job. May I have a look at your paper?

**Comment by ricardoCyy** [comment]
@QiaoFeng0419 Sorry for the late reply. Our paper just gets accepted by CEUS(Computer, environment and Urban system), it may take a while to be published. I will let you know when it is accessible. Thanks for your attention!

**Comment by ricardoCyy** [comment]
@QiaoFeng0419 Our paper is accessible now. You can download it from [research gate](https://www.researchgate.net/publication/330985511_Unravel_the_Landscape_and_Pulses_of_Cycling_Activities_From_A_Dockless_Bike-Sharing_System) or [senseable lab website](http://senseable.mit.edu/papers/pdf/20190209_Xu-etal_UnravelLandscape_CEUS.pdf)

**Comment by ghost** [comment]
Thank you.
